/*
Created a Bank application that allows for 5 user accounts to be created.
Displays each user's specific account once they've logged in 
and allows the user to manipulate the balance on their account
by depositing/withdrawing sums of their choosing. The application also 
allows for an admin to log in and see all the accounts that have been created
and particualr details of each account. It also gives the admin the ability to
permently delete any account of their choosing.
 */
package bank;
// Imported tDJOptionPane & DefultTableModel from Javax libary & Decimal format from the Java libary.

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abas Abdi 21422705
 */
public class TheBank extends javax.swing.JFrame {

    /**
     * Creates new form TheBank
     */
    public TheBank() {
        initComponents();
        this.setVisible(false);
        jFrame1.setSize(288, 325);
        jFrame3.setSize(288, 325);
        jFrame4.setSize(800, 245);
        jFrame2.setSize(284, 389);
        jFrame3.setTitle("Admin Login");
        jFrame4.setTitle("Admin Control Panel");
        jFrame1.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jFrame2 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jTextField10 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jFrame3 = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jPasswordField4 = new javax.swing.JPasswordField();
        jToggleButton5 = new javax.swing.JToggleButton();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jFrame4 = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jToggleButton4 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar9 = new javax.swing.JMenuBar();
        jMenu12 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar7 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuBar8 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();

        jFrame1.setTitle("Login");
        jFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Account Name");
        jLabel6.setToolTipText("");
        jLabel6.setName(""); // NOI18N

        jToggleButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jToggleButton2.setText("LOGIN");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Password");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank logo.png"))); // NOI18N
        jLabel11.setText("UWL Bank");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel7))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel6))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPasswordField1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jFrame1.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 270));

        jMenu1.setText("Create Account");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu4.setText("Admin");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jFrame1.setJMenuBar(jMenuBar1);

        jFrame2.setTitle("Create Account");
        jFrame2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(270, 350));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jToggleButton3.setText("Create Account");
        jToggleButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 180, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Account Name");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Balance");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Annual Interest Rate");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Password");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));
        jPanel1.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 250, 30));
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 250, 30));

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 250, 30));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 250, 30));

        jFrame2.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 350));

        jMenu2.setText("Back");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu2);

        jFrame2.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel5.setText("jLabel5");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Password");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank logo.png"))); // NOI18N
        jLabel15.setText("UWL Bank");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Admin Username");
        jLabel16.setToolTipText("");
        jLabel16.setName(""); // NOI18N

        jPasswordField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField4ActionPerformed(evt);
            }
        });

        jToggleButton5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jToggleButton5.setText("LOGIN");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14)
                            .addComponent(jPasswordField4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel15)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(10, 10, 10)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jMenu5.setText("Back");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar4.add(jMenu5);

        jFrame3.setJMenuBar(jMenuBar4);

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFrame4.setBackground(new java.awt.Color(255, 255, 255));
        jFrame4.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jTable3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Acct Name", "Balance", "Yearly Int", "Monthly Int", "Date Created"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable3.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setMinWidth(50);
            jTable3.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable3.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable3.getColumnModel().getColumn(3).setMinWidth(6);
            jTable3.getColumnModel().getColumn(3).setPreferredWidth(60);
            jTable3.getColumnModel().getColumn(5).setMinWidth(250);
            jTable3.getColumnModel().getColumn(5).setPreferredWidth(250);
        }

        jToggleButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jToggleButton4.setText("Delete Account");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(349, 349, 349)
                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jFrame4.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 210));

        jMenu12.setText("Logout");
        jMenu12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu12MouseClicked(evt);
            }
        });
        jMenuBar9.add(jMenu12);

        jFrame4.setJMenuBar(jMenuBar9);

        jMenu6.setText("File");
        jMenuBar6.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar6.add(jMenu7);

        jMenu8.setText("File");
        jMenuBar7.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar7.add(jMenu9);

        jMenu10.setText("File");
        jMenuBar8.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar8.add(jMenu11);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Balance", "Yearly Int", "Withdraw", "Deposit", "Monthly Int"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 510, 170));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Make A Deposit");

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0.00");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Make A Withdrawal");

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("0.00");

        jToggleButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jToggleButton1.setText("SUBMIT");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Account Created:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(175, 175, 175)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 240));

        jMenu3.setText("Logout");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar3.add(jMenu3);

        setJMenuBar(jMenuBar3);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Formatting the numbers 
    DecimalFormat f = new DecimalFormat("£#,###.##");
    DecimalFormat t = new DecimalFormat("##,##0.00 '%'");
// Declared the login variable outside the button so i can use it elsewhere 
    int login = 0;
    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // Checks if the values entered in the Account Name & Password fields match 
        // that of any of the accounts & if so makes the jframe visible with that accounts 
        // perticular details displayed for the user to manipulate.
        if (act1.getAccountName().equals(jTextField6.getText()) && act1.getPassword().equals(String.valueOf(jPasswordField1.getPassword()))) {
            jLabel3.setText(act1.getDateCreated().toString());
            this.setTitle(act1.getAccountName() + "'s Bank Account");
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.getDataVector().removeAllElements();
            Object[] row = {act1.getId(), f.format(act1.getBalance()), t.format(act1.getAnnualInterestRate()), f.format(act1.getWithdrawal()), f.format(act1.getDeposit()), t.format(act1.getMonthlyInterestRate())};
            model.addRow(row);
            login = 1;
            jFrame1.setVisible(false);
            this.setVisible(true);
        } else if (act2.getAccountName().equals(jTextField6.getText()) && act2.getPassword().equals(String.valueOf(jPasswordField1.getPassword()))) {
            jLabel3.setText(act2.getDateCreated().toString());
            this.setTitle(act2.getAccountName() + "'s Bank Account");
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.getDataVector().removeAllElements();
            Object[] row = {act2.getId(), f.format(act2.getBalance()), t.format(act2.getAnnualInterestRate()), f.format(act2.getWithdrawal()), f.format(act2.getDeposit()), t.format(act2.getMonthlyInterestRate())};
            model.addRow(row);
            login = 2;
            jFrame1.setVisible(false);
            this.setVisible(true);

        } else if (act3.getAccountName().equals(jTextField6.getText()) && act3.getPassword().equals(String.valueOf(jPasswordField1.getPassword()))) {
            jLabel3.setText(act3.getDateCreated().toString());
            this.setTitle(act3.getAccountName() + "'s Bank Account");
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.getDataVector().removeAllElements();
            Object[] row = {act3.getId(), f.format(act3.getBalance()), t.format(act3.getAnnualInterestRate()), f.format(act3.getWithdrawal()), f.format(act3.getDeposit()), t.format(act3.getMonthlyInterestRate())};
            model.addRow(row);
            login = 3;
            jFrame1.setVisible(false);
            this.setVisible(true);

        } else if (act4.getAccountName().equals(jTextField6.getText()) && act4.getPassword().equals(String.valueOf(jPasswordField1.getPassword()))) {
            jLabel3.setText(act4.getDateCreated().toString());
            this.setTitle(act4.getAccountName() + "'s Bank Account");
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.getDataVector().removeAllElements();
            Object[] row = {act4.getId(), f.format(act4.getBalance()), t.format(act4.getAnnualInterestRate()), f.format(act4.getWithdrawal()), f.format(act4.getDeposit()), t.format(act4.getMonthlyInterestRate())};
            model.addRow(row);
            login = 4;
            jFrame1.setVisible(false);
            this.setVisible(true);

        } else if (act5.getAccountName().equals(jTextField6.getText()) && act5.getPassword().equals(String.valueOf(jPasswordField1.getPassword()))) {
            jLabel3.setText(act5.getDateCreated().toString());
            this.setTitle(act5.getAccountName() + "'s Bank Account");
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.getDataVector().removeAllElements();
            Object[] row = {act5.getId(), f.format(act5.getBalance()), t.format(act5.getAnnualInterestRate()), f.format(act5.getWithdrawal()), f.format(act5.getDeposit()), t.format(act5.getMonthlyInterestRate())};
            model.addRow(row);
            login = 5;
            jFrame1.setVisible(false);
            this.setVisible(true);

        }

    }//GEN-LAST:event_jToggleButton2ActionPerformed

// Created the instances of the Account Object outside the button so they can be used elsewhere 
    Account act1 = new Account();
    Account act2 = new Account();
    Account act3 = new Account();
    Account act4 = new Account();
    Account act5 = new Account();
    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed

// Checks for an empty object in which to store the information (so we can have more than one account)
        if (act1.getAccountName() == null) {
            act1 = new Account(1111, jTextField8.getText(), Double.parseDouble(jTextField9.getText()),
                    Double.parseDouble(jTextField10.getText()), String.valueOf(jPasswordField2.getPassword()));

            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");
            jPasswordField2.setText("");
            JOptionPane.showMessageDialog(jFrame2,
                    "Congratulations! Your account has successfully been created.");

        } else if (act1.getAccountName() != null && act2.getAccountName() == null) {
            act2 = new Account(1112, jTextField8.getText(), Double.parseDouble(jTextField9.getText()),
                    Double.parseDouble(jTextField10.getText()), String.valueOf(jPasswordField2.getPassword()));

            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");
            jPasswordField2.setText("");
            JOptionPane.showMessageDialog(jFrame2,
                    "Congratulations! Your account has successfully been created.");

        } else if (act1.getAccountName() != null && act2.getAccountName() != null && act3.getAccountName() == null) {
            act3 = new Account(1113, jTextField8.getText(), Double.parseDouble(jTextField9.getText()),
                    Double.parseDouble(jTextField10.getText()), String.valueOf(jPasswordField2.getPassword()));

            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");
            jPasswordField2.setText("");
            JOptionPane.showMessageDialog(jFrame2,
                    "Congratulations! Your account has successfully been created.");

        } else if (act1.getAccountName() != null && act2.getAccountName() != null && act3.getAccountName() != null
                && act4.getAccountName() == null) {
            act4 = new Account(1114, jTextField8.getText(), Double.parseDouble(jTextField9.getText()),
                    Double.parseDouble(jTextField10.getText()), String.valueOf(jPasswordField2.getPassword()));

            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");
            jPasswordField2.setText("");
            JOptionPane.showMessageDialog(jFrame2,
                    "Congratulations! Your account has successfully been created.");

        } else if (act1.getAccountName() != null && act2.getAccountName() != null && act3.getAccountName() != null
                && act4.getAccountName() != null && act5.getAccountName() == null) {
            act5 = new Account(1115, jTextField8.getText(), Double.parseDouble(jTextField9.getText()),
                    Double.parseDouble(jTextField10.getText()), String.valueOf(jPasswordField2.getPassword()));

            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");
            jPasswordField2.setText("");
            JOptionPane.showMessageDialog(jFrame2,
                    "Congratulations! Your account has successfully been created.");

        }

    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

        jFrame2.setVisible(true);

    }//GEN-LAST:event_jMenu1MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // Checks which account was logged in using switch statment 
        // runs the relevant code particular to that account.
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        switch (login) {
            case 1: {
                act1.Deposit(Double.parseDouble(jTextField1.getText()));
                act1.Withdraw(Double.parseDouble(jTextField2.getText()));
                Object[] row = {act1.getId(), f.format(act1.getBalance()), t.format(act1.getAnnualInterestRate()), f.format(act1.getWithdrawal()), f.format(act1.getDeposit()), t.format(act1.getMonthlyInterestRate())};
                model.addRow(row);
                break;
            }
            case 2: {
                act2.Deposit(Double.parseDouble(jTextField1.getText()));
                act2.Withdraw(Double.parseDouble(jTextField2.getText()));
                Object[] row = {act2.getId(), f.format(act2.getBalance()), t.format(act2.getAnnualInterestRate()), f.format(act2.getWithdrawal()), f.format(act2.getDeposit()), t.format(act2.getMonthlyInterestRate())};
                model.addRow(row);
                break;
            }
            case 3: {
                act3.Deposit(Double.parseDouble(jTextField1.getText()));
                act3.Withdraw(Double.parseDouble(jTextField2.getText()));
                Object[] row = {act3.getId(), f.format(act3.getBalance()), t.format(act3.getAnnualInterestRate()), f.format(act3.getWithdrawal()), f.format(act3.getDeposit()), t.format(act3.getMonthlyInterestRate())};
                model.addRow(row);
                break;
            }
            case 4: {
                act4.Deposit(Double.parseDouble(jTextField1.getText()));
                act4.Withdraw(Double.parseDouble(jTextField2.getText()));
                Object[] row = {act4.getId(), f.format(act4.getBalance()), t.format(act4.getAnnualInterestRate()), f.format(act4.getWithdrawal()), f.format(act4.getDeposit()), t.format(act4.getMonthlyInterestRate())};
                model.addRow(row);
                break;
            }
            case 5: {
                act5.Deposit(Double.parseDouble(jTextField1.getText()));
                act5.Withdraw(Double.parseDouble(jTextField2.getText()));
                Object[] row = {act5.getId(), f.format(act5.getBalance()), t.format(act5.getAnnualInterestRate()), f.format(act5.getWithdrawal()), f.format(act5.getDeposit()), t.format(act5.getMonthlyInterestRate())};
                model.addRow(row);
                break;
            }
            default:
                break;
        }

        // Formats the text field 
        jTextField1.setText("0.00");
        jTextField2.setText("0.00");
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        //Hide jFrame2 and made jFrame1 visible.
        jFrame2.setVisible(false);
        jFrame1.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        //Hide JFrame and made jFrame1 visible.
        this.setVisible(false);
        jFrame1.setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        //Hide jFrame1 and made jFrame3 visible.
        jFrame3.setVisible(true);
        jFrame1.setVisible(false);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jPasswordField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField4ActionPerformed
    // Here we have the username and password for the Admin
    String Admin = "Admin";
    String Password = "AdminPass22";
    // Gives the user three tries to get it right before locking them out 
    int tries = 0;
    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // Only displays to the Admin the accounts that have been registered.
        if (jTextField11.getText().equals(Admin) && String.valueOf(jPasswordField4.getPassword()).equals(Password) && tries < 5) {
            DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
            model.getDataVector().removeAllElements();
            if (act1.getAccountName() != null) {
                Object[] row1 = {act1.getId(), act1.getAccountName(), f.format(act1.getBalance()), t.format(act1.getAnnualInterestRate()), t.format(act1.getMonthlyInterestRate()), act1.getDateCreated()};
                model.addRow(row1);
            }
            if (act2.getAccountName() != null) {
                Object[] row2 = {act2.getId(), act2.getAccountName(), f.format(act2.getBalance()), t.format(act2.getAnnualInterestRate()), t.format(act2.getMonthlyInterestRate()), act2.getDateCreated()};
                model.addRow(row2);
            }
            if (act3.getAccountName() != null) {
                Object[] row3 = {act3.getId(), act3.getAccountName(), f.format(act3.getBalance()), t.format(act3.getAnnualInterestRate()), t.format(act3.getMonthlyInterestRate()), act3.getDateCreated()};
                model.addRow(row3);
            }
            if (act4.getAccountName() != null) {
                Object[] row4 = {act4.getId(), act4.getAccountName(), f.format(act4.getBalance()), t.format(act4.getAnnualInterestRate()), t.format(act4.getMonthlyInterestRate()), act4.getDateCreated()};
                model.addRow(row4);
            }
            if (act5.getAccountName() != null) {
                Object[] row5 = {act5.getId(), act5.getAccountName(), f.format(act5.getBalance()), t.format(act5.getAnnualInterestRate()), t.format(act5.getMonthlyInterestRate()), act5.getDateCreated()};
                model.addRow(row5);
            }

            jFrame4.setVisible(true);
        } else {
            // Increments the number of tries by one each time the user enters the wrong details.
            tries = tries + 1;
        }
        // Displays error message after the third attempt to inform them that they've been locked out.
        if (tries == 4) {
            JOptionPane.showMessageDialog(jFrame4,
                    "Sorry but you've entered the wrong Username/Password\ntoo many times and have been locked out for this session.",
                    "ACCESS DENIED",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        //Hide jFrame3 and made jFrame1 visible.
        jFrame3.setVisible(false);
        jFrame1.setVisible(true);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // Each account has a particular row assigned to it in the jTable so depending upon which
        // row the admin selects, it will reset that accounts details back to it's default settings & delete the row.
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        int rowIndex = jTable3.getSelectedRow();
        if (rowIndex == 0) {
            act1.setId(0);
            act1.setBalance(0);
            act1.setAnnualInterestRate(0);
            act1.setAccountName(null);
            act1.setPassword(null);
            act1.setDateCreated(null);
        }
        if (rowIndex == 1) {
            act2.setId(0);
            act2.setBalance(0);
            act2.setAnnualInterestRate(0);
            act2.setAccountName(null);
            act2.setPassword(null);
            act2.setDateCreated(null);
        }
        if (rowIndex == 2) {
            act3.setId(0);
            act3.setBalance(0);
            act3.setAnnualInterestRate(0);
            act3.setAccountName(null);
            act3.setPassword(null);
            act3.setDateCreated(null);
        }
        if (rowIndex == 3) {
            act4.setId(0);
            act4.setBalance(0);
            act4.setAnnualInterestRate(0);
            act4.setAccountName(null);
            act4.setPassword(null);
            act4.setDateCreated(null);
        }
        if (rowIndex == 4) {
            act5.setId(0);
            act5.setBalance(0);
            act5.setAnnualInterestRate(0);
            act5.setAccountName(null);
            act5.setPassword(null);
            act5.setDateCreated(null);
        }
        model.removeRow(rowIndex);
        //This will close the users account if they are logged in.
        if (act1.getAccountName() == null && login == 1) {
            this.setVisible(false);
            jFrame1.setVisible(true);
        } else if (act2.getAccountName() == null && login == 2) {
            this.setVisible(false);
            jFrame1.setVisible(true);
        } else if (act3.getAccountName() == null && login == 3) {
            this.setVisible(false);
            jFrame1.setVisible(true);
        } else if (act4.getAccountName() == null && login == 4) {
            this.setVisible(false);
            jFrame1.setVisible(true);
        } else if (act5.getAccountName() == null && login == 5) {
            this.setVisible(false);
            jFrame1.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jMenu12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu12MouseClicked
        jFrame4.setVisible(false);
        jFrame1.setVisible(true);
    }//GEN-LAST:event_jMenu12MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Remmoves all elements in the jTable and repopulates it so figures can be updated 
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.getDataVector().removeAllElements();
        if (act1.getAccountName() != null) {
            Object[] row1 = {act1.getId(), act1.getAccountName(), f.format(act1.getBalance()), t.format(act1.getAnnualInterestRate()), t.format(act1.getMonthlyInterestRate()), act1.getDateCreated()};
            model.addRow(row1);
        }
        if (act2.getAccountName() != null) {
            Object[] row2 = {act2.getId(), act2.getAccountName(), f.format(act2.getBalance()), t.format(act2.getAnnualInterestRate()), t.format(act2.getMonthlyInterestRate()), act2.getDateCreated()};
            model.addRow(row2);
        }
        if (act3.getAccountName() != null) {
            Object[] row3 = {act3.getId(), act3.getAccountName(), f.format(act3.getBalance()), t.format(act3.getAnnualInterestRate()), t.format(act3.getMonthlyInterestRate()), act3.getDateCreated()};
            model.addRow(row3);
        }
        if (act4.getAccountName() != null) {
            Object[] row4 = {act4.getId(), act4.getAccountName(), f.format(act4.getBalance()), t.format(act4.getAnnualInterestRate()), t.format(act4.getMonthlyInterestRate()), act4.getDateCreated()};
            model.addRow(row4);
        }
        if (act5.getAccountName() != null) {
            Object[] row5 = {act5.getId(), act5.getAccountName(), f.format(act5.getBalance()), t.format(act5.getAnnualInterestRate()), t.format(act5.getMonthlyInterestRate()), act5.getDateCreated()};
            model.addRow(row5);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheBank().setVisible(false);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JMenuBar jMenuBar8;
    private javax.swing.JMenuBar jMenuBar9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    // End of variables declaration//GEN-END:variables
}
